In [1]:
import pandas as pd
import numpy as np
import os
from scipy.optimize import LinearConstraint
from scipy.optimize import minimize
from scipy.optimize import NonlinearConstraint

os.chdir(r'C:\Users\Daniel\Documents\Johns Hopkins\Fall 2021\Stochastic Processes I\Project')

In [2]:
data = pd.read_csv('Stock Data.csv')
dates = list(data.Date.unique())
stocks = list(data.Name.unique())

data.drop(['Open', 'High', 'Low', 'Volume'],axis=1, inplace = True)
df = pd.pivot_table(data, values= 'Close' , index = 'Name', columns = 'Date')
df.fillna(method='ffill', inplace = True)
df.fillna(method='ffill', inplace = True)

In [92]:
S = []
for j in range(len(stocks)):
    S.append(0)

one_over_T = 1/(len(dates))
for i in range(len(dates)):
    a = np.array(df[dates[i]])[np.newaxis]
    s = one_over_T *np.dot(a.T,a)
    S = S+s

In [104]:
S1 = []
for j in range(len(stocks)):
    S1.append(0)

one_over_T_minus_1 = 1/(len(dates)-1)
for i in range(len(dates)-1):
    a = np.array(df[dates[i]])[np.newaxis]
    b = np.array(df[dates[i+1]])[np.newaxis]
    s1 = one_over_T_minus_1  *np.dot(a.T,b)
    S1 = S1+s1

In [150]:
m = []
for j in range(len(stocks)):
    m.append(1)
M= np.eye(len(stocks))

def summation(M):
    return sum(abs(M))
def constraint(M):
    return np.amax(abs(np.dot(S,M)-np.transpose(S1)))
con = {'type':'ineq', 'fun':constraint}
nlc = NonlinearConstraint(constraint, 0, .1)


In [151]:
A=minimize(summation, x0 =m, constraints = nlc).x
A

array([ 1.83493411e-02,  2.24883742e-01, -6.35066978e-01, -4.55020270e+00,
        1.94735241e-01, -2.28987271e-01, -1.20114234e+00,  1.48135928e+00,
        2.25817409e-01, -2.09082735e+00,  2.40629141e+00, -1.25268756e-01,
       -4.80902924e-01, -1.56357140e-03, -1.09331122e+00, -3.24997991e-01,
       -4.01951109e-01,  3.70977619e-01,  2.76660617e-02, -1.98679035e+00,
        7.16196086e-01, -4.60694748e+00,  2.79138863e-01,  1.51220927e-01,
        9.08261600e-02, -9.30001089e-02, -2.13613871e-01, -1.62112630e-01,
       -6.06187119e-02, -5.10326733e-03,  3.98781739e-01])

In [152]:
minimize(summation, x0=m, constraints = con)

     fun: 0.00909757774708872
     jac: array([-1.,  1., -1.,  1.,  1.,  1., -1.,  1.,  1., -1.,  1., -1.,  1.,
       -1., -1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1.,  1., -1.,
        1.,  1., -1.,  1.,  1.])
 message: 'Optimization terminated successfully'
    nfev: 919
     nit: 25
    njev: 25
  status: 0
 success: True
       x: array([-6.13537069e-05,  3.51434567e-05, -3.24037270e-03,  1.81472789e-04,
        9.64697109e-06,  3.97972559e-05, -7.36930277e-05,  3.46636493e-04,
        2.08607331e-04, -6.77985400e-05,  4.83882387e-05, -3.76411453e-04,
        8.40093425e-04, -6.63727472e-04, -1.69938008e-04,  4.53564650e-04,
        2.59916384e-05,  1.33545067e-06,  3.76421421e-04,  4.61680845e-04,
        8.18209960e-05, -2.35625744e-05, -6.16968758e-07, -1.57335619e-04,
        1.23953275e-04, -2.07271363e-05,  2.79228193e-04,  4.03720005e-04,
       -2.61137268e-05,  1.73221338e-04,  1.25203046e-04])

In [168]:
v = [row[0] for row in M]
Sj = [row[0] for row in S1.T]
(np.dot(S,v) - Sj)

array([0.95833414, 1.33309189, 8.86483083, 1.13305025, 2.03099465,
       1.27158207, 0.34423874, 1.43883107, 0.97979726, 0.46929788,
       9.8978272 , 2.44513121, 1.6698185 , 2.11145557, 0.50224844,
       1.52033404, 0.99217877, 0.53741666, 1.53265803, 2.30939374,
       0.66781398, 0.77849441, 0.55847755, 0.43402329, 1.14330701,
       1.45993381, 1.960684  , 1.37713544, 0.65713397, 0.97734076,
       1.07352346])

In [24]:
Err = []
for j in range(len(stocks)):
    Err.append(0)

one_over_T = 1/(len(dates))
for i in range(len(dates)-1):
    a = np.array(df[dates[i]])
    b = np.array(df[dates[i+1]])
    err =one_over_T* (abs(b - (A*a))/b)
    Err = Err+err

In [25]:
max(abs((S*A)-np.transpose(S1)))

28861.801055264667

In [153]:
np.amax(abs((np.dot(S,A) - np.transpose(S1))))

113883.55685389246

In [64]:
A

array([-4.33652178e-08, -4.33652172e-08, -3.20019845e-06, -4.33652168e-08,
       -4.33652169e-08, -4.33652169e-08, -4.33652168e-08, -4.33652169e-08,
       -4.33652169e-08, -4.33652168e-08, -2.48783353e-07, -4.33652168e-08,
       -4.33652167e-08, -4.33652168e-08, -4.33652168e-08, -4.33652167e-08,
       -4.33652167e-08, -4.33652168e-08, -4.33652169e-08, -4.33652169e-08,
       -4.33652171e-08, -4.33652171e-08, -4.33652171e-08, -4.33652173e-08,
       -4.33652175e-08, -4.33652175e-08, -4.33652174e-08, -4.33652173e-08,
       -4.33652172e-08, -4.33652172e-08, -4.33652173e-08])

In [162]:
S*m - np.transpose(S1)

TypeError: unsupported operand type(s) for *: 'float' and 'OptimizeResult'

In [117]:
np.amax(abs(np.dot(S,M) - S1))

201.2858818831155

In [124]:
np.dot(S,M).shape

(31, 31)

In [125]:
S1.shape

(31, 31)

array([0.95833414, 1.33309189, 8.86483083, 1.13305025, 2.03099465,
       1.27158207, 0.34423874, 1.43883107, 0.97979726, 0.46929788,
       9.8978272 , 2.44513121, 1.6698185 , 2.11145557, 0.50224844,
       1.52033404, 0.99217877, 0.53741666, 1.53265803, 2.30939374,
       0.66781398, 0.77849441, 0.55847755, 0.43402329, 1.14330701,
       1.45993381, 1.960684  , 1.37713544, 0.65713397, 0.97734076,
       1.07352346])

In [164]:
S

array([[   982.76843123,   2261.6779951 ,  11369.98432096,
          1894.43579205,   3472.0871493 ,   2435.47053338,
           734.11293384,   2794.38549675,   1972.35956507,
           755.94168523,  14749.41326874,   5072.6209657 ,
          2396.81933344,   4198.93962778,    795.55205851,
          2574.17552858,   1656.32990156,   1031.52580566,
          2658.34442113,   3696.62400513,   1416.8245805 ,
          1207.64668546,   1015.52758003,    795.96778765,
          2136.56445159,   2390.05624066,   2644.75431854,
          2630.47139348,   1237.50913921,   1879.82483169,
          2348.41166083],
       [  2261.6779951 ,   6162.47103384,  30607.89087811,
          4485.09556652,   8334.12868715,   5813.96364636,
          1675.57939626,   6714.77487427,   5035.00275603,
          1618.34243007,  37271.85203679,  11369.0899143 ,
          6136.37782719,  10450.1561844 ,   1909.68488295,
          6180.35088156,   3919.95960099,   2525.90395781,
          6746.32163417,   906