In [1]:
import pandas as pd
import numpy as np
import os
from scipy.optimize import LinearConstraint
from scipy.optimize import minimize
from scipy.optimize import NonlinearConstraint

os.chdir(r'C:\Users\Daniel\Documents\Johns Hopkins\Fall 2021\Stochastic Processes I\Project')

In [2]:
data = pd.read_csv('Stock Data.csv')
dates = list(data.Date.unique())
stocks = list(data.Name.unique())

data.drop(['Open', 'High', 'Low', 'Volume'],axis=1, inplace = True)
df = pd.pivot_table(data, values= 'Close' , index = 'Name', columns = 'Date')
df.fillna(method='ffill', inplace = True)
df.fillna(method='ffill', inplace = True)

In [3]:
S = []
for j in range(len(stocks)):
    S.append(0)

one_over_T = 1/(len(dates))
for i in range(len(dates)):
    a = np.array(df[dates[i]])
    s = one_over_T *(a*np.transpose(a))
    S = S+s

In [4]:
S1 = []
for j in range(len(stocks)):
    S1.append(0)

one_over_T_minus_1 = 1/(len(dates)-1)
for i in range(len(dates)-1):
    a = np.array(df[dates[i]])
    b = np.array(df[dates[i+1]])
    s1 = one_over_T_minus_1  *(a*np.transpose(b))
    S1 = S1+s1

In [52]:
m = []
for j in range(len(stocks)):
    m.append(1)
M= np.eye(len(stocks))

def summation(M):
    return sum(abs(M))
def constraint(M):
    return np.amax(abs((S*M)-np.transpose(S1)))
con = {'type':'ineq', 'fun':constraint}
nlc = NonlinearConstraint(constraint, 0, 1)

In [53]:
A=minimize(summation, M, constraints = nlc).x
A

ValueError: `x0` must have at most 1 dimension.

In [34]:
minimize(summation, M, constraints = con)

     fun: 4.70657309686412e-06
     jac: array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1.])
 message: 'Optimization terminated successfully'
    nfev: 557
     nit: 16
    njev: 16
  status: 0
 success: True
       x: array([-4.33652178e-08, -4.33652172e-08, -3.20019845e-06, -4.33652168e-08,
       -4.33652169e-08, -4.33652169e-08, -4.33652168e-08, -4.33652169e-08,
       -4.33652169e-08, -4.33652168e-08, -2.48783353e-07, -4.33652168e-08,
       -4.33652167e-08, -4.33652168e-08, -4.33652168e-08, -4.33652167e-08,
       -4.33652167e-08, -4.33652168e-08, -4.33652169e-08, -4.33652169e-08,
       -4.33652171e-08, -4.33652171e-08, -4.33652171e-08, -4.33652173e-08,
       -4.33652175e-08, -4.33652175e-08, -4.33652174e-08, -4.33652173e-08,
       -4.33652172e-08, -4.33652172e-08, -4.33652173e-08])

In [24]:
Err = []
for j in range(len(stocks)):
    Err.append(0)

one_over_T = 1/(len(dates))
for i in range(len(dates)-1):
    a = np.array(df[dates[i]])
    b = np.array(df[dates[i+1]])
    err =one_over_T* (abs(b - (A*a))/b)
    Err = Err+err

In [25]:
max(abs((S*A)-np.transpose(S1)))

28861.801055264667

In [51]:
np.amax(abs((S*M - np.transpose(S1))))

238822.34531255387

In [294]:
(S*A) - np.transpose(S1)

array([-1749.97194946, -4349.7816319 , -2939.37959698, -4017.90349364,
       -4015.25446979, -4374.24014187, -1076.15666315, -4348.25435335,
       -4375.00673069, -1222.26396382,  2942.2927906 , -4015.57278727,
       -3986.05470838, -3011.2710632 , -1236.0583978 , -4389.69141151,
       -4373.2301825 , -2175.77241028, -4367.3858274 , -3489.33096601,
       -3928.18549585, -2758.83166964, -2120.83714213, -1228.67837702,
       -4294.84816083, -4373.15266053, -3482.74776317, -4376.44387694,
       -3121.21084134, -3992.58099336, -4390.23519686])

In [162]:
S*m - np.transpose(S1)

TypeError: unsupported operand type(s) for *: 'float' and 'OptimizeResult'

In [76]:
data

Date  Close  Name
0      2006-01-03  79.11   MMM
1      2006-01-04  78.71   MMM
2      2006-01-05  77.99   MMM
3      2006-01-06  78.63   MMM
4      2006-01-09  79.02   MMM
...           ...    ...   ...
93607  2017-12-22  71.58  AABA
93608  2017-12-26  69.86  AABA
93609  2017-12-27  70.06  AABA
93610  2017-12-28  69.82  AABA
93611  2017-12-29  69.85  AABA

[93612 rows x 3 columns]

In [48]:
table = pd.pivot_table(data, values= 'Close' , index = 'Name', columns = 'Date')

In [85]:
df[[dates[0],dates[1]]]

Date   2006-01-03  2006-01-04
Name                         
AABA        40.91       40.97
AAPL        10.68       10.71
AMZN        47.58       47.25
AXP         52.58       51.95
BA          70.44       71.17
CAT         57.80       59.27
CSCO        17.45       17.85
CVX         59.08       58.91
DIS         24.40       23.99
GE          35.37       35.32
GOOGL      217.83      222.84
GS         128.87      127.09
HD          41.24       40.48
IBM         82.06       81.95
INTC        25.57       25.91
JNJ         61.63       62.58
JPM         40.19       39.62
KO          20.45       20.41
MCD         33.52       33.82
MMM         79.11       78.71
MRK         32.75       33.13
MSFT        26.84       26.97
NKE         10.74       10.69
PFE         23.78       24.55
PG          58.78       58.89
TRV         45.99       46.50
UNH         61.73       61.88
UTX         56.53       56.19
VZ          30.38       31.27
WMT         46.23       46.32
XOM         58.47       58.57

In [123]:
S

array([   982.76843123,   6162.47103384, 167939.15237175,   3901.76188275,
        12559.16102424,   6915.6413154 ,    604.39448821,   9331.19826056,
         4338.26892546,    686.09606238, 238982.24309334,  28976.63939728,
         6414.61389881,  22612.38018146,    696.0389103 ,   7114.80115235,
         2914.39295974,   1221.26655901,   8095.12905894,  14492.10560831,
         2205.23662722,   1549.04856265,   1190.61511573,    689.71123291,
         5162.73803689,   6190.42087013,   7660.46843573,   7673.13009722,
         1751.97737285,   4041.27824192,   6671.04020967])

In [95]:
s

array([1.61557036e+00, 9.48304401e+00, 4.52867576e+02, 3.26572056e+00,
       2.87986451e+01, 8.22233656e+00, 4.85725166e-01, 5.18958149e+00,
       3.82728480e+00, 1.00828642e-01, 3.67434291e+02, 2.14909462e+01,
       1.18945765e+01, 7.79393921e+00, 7.05544901e-01, 6.46413192e+00,
       3.78680914e+00, 6.97011391e-01, 9.80970013e+00, 1.83440520e+01,
       1.04844798e+00, 2.42287801e+00, 1.29553063e+00, 4.34400132e-01,
       2.79534252e+00, 6.09212238e+00, 1.60935800e+01, 5.38877646e+00,
       9.27677119e-01, 3.22899421e+00, 2.31644026e+00])

In [98]:

S

array([           nan,            nan,            nan,  3901.76188275,
       12559.16102424,  6915.6413154 ,            nan,  9331.19826056,
        4338.26892546,   686.09606238,            nan, 28976.63939728,
        6414.61389881, 22612.38018146,            nan,  7114.80115235,
        2914.39295974,  1221.26655901,  8095.12905894, 14492.10560831,
                  nan,            nan,  1190.61511573,   689.71123291,
        5162.73803689,  6190.42087013,  7660.46843573,  7673.13009722,
        1751.97737285,  4041.27824192,  6671.04020967])

In [99]:
dates

['2006-01-03',
 '2006-01-04',
 '2006-01-05',
 '2006-01-06',
 '2006-01-09',
 '2006-01-10',
 '2006-01-11',
 '2006-01-12',
 '2006-01-13',
 '2006-01-17',
 '2006-01-18',
 '2006-01-19',
 '2006-01-20',
 '2006-01-23',
 '2006-01-24',
 '2006-01-25',
 '2006-01-26',
 '2006-01-27',
 '2006-01-30',
 '2006-01-31',
 '2006-02-01',
 '2006-02-02',
 '2006-02-03',
 '2006-02-06',
 '2006-02-07',
 '2006-02-08',
 '2006-02-09',
 '2006-02-10',
 '2006-02-13',
 '2006-02-14',
 '2006-02-15',
 '2006-02-16',
 '2006-02-17',
 '2006-02-21',
 '2006-02-22',
 '2006-02-23',
 '2006-02-24',
 '2006-02-27',
 '2006-02-28',
 '2006-03-01',
 '2006-03-02',
 '2006-03-03',
 '2006-03-06',
 '2006-03-07',
 '2006-03-08',
 '2006-03-09',
 '2006-03-10',
 '2006-03-13',
 '2006-03-14',
 '2006-03-15',
 '2006-03-16',
 '2006-03-17',
 '2006-03-20',
 '2006-03-21',
 '2006-03-22',
 '2006-03-23',
 '2006-03-24',
 '2006-03-27',
 '2006-03-28',
 '2006-03-29',
 '2006-03-30',
 '2006-03-31',
 '2006-04-03',
 '2006-04-04',
 '2006-04-05',
 '2006-04-06',
 '2006-04-

In [125]:
dates

Index(['1/10/2006', '1/10/2007', '1/10/2008', '1/10/2011', '1/10/2012',
       '1/10/2013', '1/10/2014', '1/10/2017', '1/11/2006', '1/11/2007',
       ...
       '9/8/2016', '9/8/2017', '9/9/2008', '9/9/2009', '9/9/2010', '9/9/2011',
       '9/9/2013', '9/9/2014', '9/9/2015', '9/9/2016'],
      dtype='object', name='Date', length=3020)

In [116]:
df1 = df[df.isna().any(axis=1)]

In [54]:
import os
current_path = os.getcwd()

In [56]:
pwd

'C:\\Users\\Daniel\\Documents\\Johns Hopkins\\Fall 2021\\Stochastic Processes I\\Project'